### ISSUE TITLE
messageKey required where appKey was not

### ISSUE THREAD

**Issue by SeaPea** [pebble/clay#109]
In the latest release that changed appKey to messageKey there appears to have been a fundamental change in that the messageKey keys now have to be defined in the app json.

I understand the reason for the main use case where the settings are being passed automatically to the C code, but in my watch face there is not a one to one mapping of settings to message keys as I perform some actions on settings in the JS before passing to the C code. In the previous versions of Clay I was able to define an independent set of appKey keys, which then took care of saving and returning the setting as JSON and with autoHandleEvents set to false I could then perform various actions before sending data to the C code. 

Since my config.js messageKeys do not match my app json message keys, when I call clay.getSettings(e.response) in the latest version I get the following output, which was a little confusing at first:

{"NaN":0}

Unless I am missing something it seems that to replicate the previous behavior I would have to switch to using IDs only with userData and a custom function to restore and retrieve all the settings, which will be quite tedious with all the settings I have.

Any chance the previous behavior can be restored somehow, like through a setting? 

(It could also do with throwing an error if a messageKey is not found instead of returning the JSON above.)

**Comment by SeaPea** [comment]
While I could add all my missing messageKeys to the app json, it seems doing this returns the key number in the json instead of the key name.

**Comment by keegan-lillo** [comment]
Have a look at https://developer.pebble.com/guides/communication/using-pebblekit-js/#sending-messages-from-js

```javascript
// Require the keys' numeric values.
var keys = require('message_keys');

// Build a dictionary.
var dict = {}
dict[keys.LapTimes] = 42
dict[keys.LapTimes+1] = 51

// Send the object
Pebble.sendAppMessage(dict, function() {
  console.log('Message sent successfully: ' + JSON.stringify(dict));
}, function(e) {
  console.log('Message failed: ' + JSON.stringify(e));
});
```
Clay also uses the `message_keys` module to get the correct value for the message keys. 

This should also help you no? https://github.com/pebble/clay/issues/71

**Comment by keegan-lillo** [comment]
I also updated the migration guide with this change https://github.com/pebble/clay#claygetsettings-will-now-by-default-return-an-object-where-the-keys-are-numbers

**Comment by keegan-lillo** [comment]
Closing since I'm pretty sure the question was answered. Please add more if you feel like this doesn't solve your issue.

**Comment by SeaPea** [comment]
Yeah I figured as much. Thank you for taking the time to respond (and quickly).

I have a dozen or more settings with multiple references to each entry from the old name/value structure in my JS, so until I get around to rewriting I think I'll stick with v0.1.7 for now.
