### ISSUE TITLE
'Description' property for each component

### ISSUE THREAD

**Issue by gregoiresage** [pebble/clay#11]
Currently, the only way to display a description for a component is to use the 'text' component but it doesn't look good.
I would like to use a 'description' that would be displayed under the component with a smaller font.

Do you see a better solution ? I tried to play with html in the "label" but the <em> <small> <i> ... tags don't seem to work

**Comment by keegan-lillo** [comment]
yeh this would be a pretty simple fix. Thanks for the feedback :)
