### ISSUE TITLE
Setting values in Clay from Javascript

### ISSUE THREAD

**Issue by PeterSumm** [pebble/clay#114]
I'm looking to get my existing apps to use Clay, but I need to preserve my users' settings that are currently stored elsewhere in LocalStorage on the phone.

Is there a preferred way of writing values back into Clay's storage?

Code examples would be great if anyone has them.

Thanks.

**Comment by keegan-lillo** [comment]
Not that is currently supported. https://github.com/pebble/clay/issues/77 is one solution if you want to submit a PR ;)

Thanks for the feedback. I'm going to close this as a duplicate.
