### ISSUE TITLE
Add dataType to config items

### ISSUE THREAD

**Issue by keegan-lillo** [pebble/clay#117]
Add a `dataType` field to config items to dictate what type conversion we want to perform for appMessage. 

eg:

``` javascript
{
  "type": "input",
  "messageKey": "num_fruit",
  "defaultValue": 5,
  "label": "Number of fruit",
  "dataType": "NUMBER"
  "attributes": {
    "type": "number"
  }
}
```

Types: here https://developer.pebble.com/guides/communication/using-pebblekit-js/#type-conversion

**Comment by gregoiresage** [comment]
Any ETA for this Clay 1.2.0 and this feature in particular ? :-p
