### ISSUE TITLE
Add 'configurable' capability in package.json

### ISSUE THREAD

**Issue by gregoiresage** [pebble/clay#123]
An app using Clay need to be configurable. So it is clever to add this capability directly in the package.
The capability should be merged with other ones in the final app

**Comment by keegan-lillo** [comment]
Did not know you could do that! nice!

**Comment by gregoiresage** [comment]
https://developer.pebble.com/sdk/changelogs/3.13.1/

**Comment by gregoiresage** [comment]
I will not make a PR for that :p
