### ISSUE TITLE
Date Time Picker

### ISSUE THREAD

**Issue by mannd** [pebble/clay#133]
A date-time picker is available for pebble/slate.  I am unable to migrate my config to clay because of the lack of a date-time picker.  Would be nice to add this control to clay.

**Comment by keegan-lillo** [comment]
It does using the `attributes` property

```js
{
  "type": "input",
  "label": "date",
  "attributes": {
    "type": "date"
  }
},
{
  "type": "input",
  "label": "time",
  "attributes": {
    "type": "time"
  }
}
```
https://github.com/pebble/clay#input

**Comment by mannd** [comment]
Does this just interpret the text input as a date or time? Or does the control appear as a date or time picker if these attributes are set?

**Comment by keegan-lillo** [comment]
The OS will show native controls.
