### ISSUE TITLE
provide a URL to open in device browser

### ISSUE THREAD

**Issue by drbourbon** [pebble/clay#136]
Hi, is there a way to configure a section with an URL so that the link opens in the phone browser?

I've tried this but it doesn't seem to work:
`{"type": "text", "defaultValue": "<a href='http://pebble.com' target='_blank'>open url sample</a>"}`

Thanks for the clay library!

**Comment by keegan-lillo** [comment]
Unfortunately, no. This is a limitation in the mobile apps.
