### ISSUE TITLE
Support for accessing camera!

### ISSUE THREAD

**Issue by wiseman13** [pebble/clay#140]
To support QR code scanning it would be great if we could access the camera. I am not sure if this is a Clay limiation or a Pebble limitation on the configuration pages. #feature

**Comment by keegan-lillo** [comment]
Sounds like a job for a custom component. You can do it with the following now though. 

config item:
```js
{
  "type": "input",
  "id": "photo",
  "label": "Tap here to choose a photo of the QR code",
  "attributes": {
    "type": "file"
  }
}
```

In the `AFTER_BUILD` handler your custom function:

```js
clayConfig.getItemById('photo').on('change', function(event) {
  // Get a reference to the taken picture or chosen file
  var files = event.target.files;
  var file;
  if (files && files.length > 0) {
    file = files[0];
  }
  
  // do something with `file`
});
```

taken from: https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/API/Camera_API/Introduction

I haven't actually tried this. It is very possible that the webviews are sandboxed to not allow file input boxes. If thats the case then I do not think there is much you can do without changes in the mobile apps.
