### ISSUE TITLE
Ambiguous use of app.js on CloudPebble

### ISSUE THREAD

**Issue by turvas** [pebble/clay#141]
In CloudPebble logs is following:

```
[PHONE] pebble-app.js:?: myAppName:325 JavaScript Error:
Error: Cannot find module './src/pkjs/index'
    at Object.loader.require (loader.js:67:11)
    at node_modules/pebble-clay/index.js:20:14
    at node_modules/pebble-clay/index.js:21:5
    at node_modules/pebble-clay/index.js:22:3
```

environment:
Android 6, Pebble App in phone 4.0.0
app.js and config.js copied from manuals, 
In CloudPebble settings: 
  JS Handling=CommonJS, 
  MESSAGE KEY ASSIGNMENT KIND = Automatic

**Comment by cjwilliams** [comment]
If you don't include Clay, does this error occur? Any chance your project or PBW can be shared? It looks like you're trying to require a path that is incorrect. If your index.js file is a sibling of the file you're requiring it from (on CP, I am almost certain this is the case), the require should read `require('./index.js')`

**Comment by turvas** [comment]
without Clay everything works.
PBW is attached.
please find screenshots attached
for build to succeed I have empty index.js, I do not include index.js from
anywhere, but if this file is not part of project, build fails with
following:

APLITE APP MEMORY USAGE
Total size of resources:        4299 bytes / 128KB
Total footprint in RAM:         7141 bytes / 24KB
Free RAM available (heap):      17435 bytes
-------------------------------------------------------
[61/69] aplite | merge_js: src/pkjs/config.js
build/js/message_keys.json
../../app/sdk3/pebble/common/include/safe.js
node_modules/pebble-clay/dist/js/index.js -> build/pebble-js-app.js
[63/69] diorite | pebble-app.raw.bin: build/diorite/pebble-app.elf ->
build/diorite/pebble-app.raw.bin
[63/69] basalt | pebble-app.raw.bin: build/basalt/pebble-app.elf ->
build/basalt/pebble-app.raw.bin
[64/69] chalk | pebble-app.raw.bin: build/chalk/pebble-app.elf ->
build/chalk/pebble-app.raw.bin
[64/69] aplite | pebble-app.raw.bin: build/aplite/pebble-app.elf ->
build/aplite/pebble-app.raw.bin
Waf: Leaving directory `/tmp/tmpWsNTIh/build'Build failed
Traceback (most recent call last):
  File "/app/sdk3/pebble/.waf-1.7.11-a9617f5a888a48865f8452474dc31b3f/waflib/Task.py",
line 123, in process
    ret=self.run()
  File "/app/sdk3/pebble/.waf-1.7.11-a9617f5a888a48865f8452474dc31b3f/waflib/Task.py",
line 47, in run
    return m1(self)
  File "/app/sdk3/pebble/.waf-1.7.11-a9617f5a888a48865f8452474dc31b3f/waflib/extras/process_js.py",
line 144, in run
    bld.fatal("\n\nJS entry file '{}' not found in JS source files
'{}'. We expect to find ""a javascript file here that we will execute
directly when your app launches.""\n\nIf you are an advanced user, you
can supply the 'js_entry_file' ""parameter to 'pbl_bundle' in your
wscript to change the default entry point."" Note that doing this will
break CloudPebble compatibility.".format(js_entry_file,js_nodes))
  File "/app/sdk3/pebble/.waf-1.7.11-a9617f5a888a48865f8452474dc31b3f/waflib/Context.py",
line 219, in fatal
    raise self.errors.ConfigurationError(msg,ex=ex)
ConfigurationError:

JS entry file 'src/pkjs/index.js' not found in JS source files
'[/tmp/tmpWsNTIh/src/pkjs/config.js,
/tmp/tmpWsNTIh/build/js/message_keys.json,
/app/sdk3/pebble/common/include/safe.js,
/tmp/tmpWsNTIh/node_modules/pebble-clay/dist/js/index.js]'. We expect
to find a javascript file here that we will execute directly when your
app launches.

If you are an advanced user, you can supply the 'js_entry_file'
parameter to 'pbl_bundle' in your wscript to change the default entry
point. Note that doing this will break CloudPebble compatibility.

**Comment by keegan-lillo** [comment]
I don't think github works with file attachments.

**Comment by cjwilliams** [comment]
I'm afraid you can't attach files to a GitHub issue like that. Can you please upload the file someplace and post the link? Alternatively, if you're on http://discord.gg/aRUAYFN, we can also try to help you there.

**Comment by turvas** [comment]
hi,

links to attached files:
https://drive.google.com/open?id=0B9qrql2OMESsclVQVFl5UkJ0Zlc3WG5QZm9kYTBrS2pWWE5n
https://drive.google.com/open?id=0B9qrql2OMESsSlV6VGdMWVliM1o0OGFqdktfS0M3bWdlY0Rz
https://drive.google.com/open?id=0B9qrql2OMESsRWhUQkFuTHdRLUFBbHNXbHNfbHN0UzhxVlBJ

brg,

**Comment by keegan-lillo** [comment]
You must use `index.js` not `app.js`. Need to updated the docs.
