### ISSUE TITLE
No Emery support

### ISSUE THREAD

**Issue by steveway** [pebble/clay#146]
Trying to build my project using the Cloudpebble beta I get the following error when compiling:
> Library pebble-clay is missing the emery platform folder in binaries

This did not happen before with the other supported targets.

**Comment by keegan-lillo** [comment]
Just published a new version to NPM. Thanks for the heads up :)

**Comment by ec1oud** [comment]
`Library pebble-clay is missing a binary for the [] platform`
Same thing?  I get it when building https://github.com/antgiant/Astronomical_Analog or https://github.com/min2sia/pebble-solar-watch for example
