### ISSUE TITLE
Can't Install Pebble Clay

### ISSUE THREAD

**Issue by Allen-B1** [pebble/clay#158]
I'm using CloudPebble. I entered pebble-clay and ^1.0.0 in the dependencies, but when I try to build, I get an error saying

```
WARNING in ./~/pebble-clay/dist/js/index.js
Critical dependencies:
2:418-425 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/pebble-clay/dist/js/index.js 2:418-425

ERROR in /app/sdk3/pebble/common/include/_message_key_wrapper.js
Module not found: Error: Cannot resolve module 'message_keys' in /app/sdk3/pebble/common/include
 @ /app/sdk3/pebble/common/include/_message_key_wrapper.js 3:36-59
```

**Comment by keegan-lillo** [comment]
Can you please post your app.js? I have a feeling you are calling clay inside your 'ready' handler

**Comment by Allen-B1** [comment]
I don't have one. All I have is main.c and index.js.

**Comment by keegan-lillo** [comment]
Sorry. Yes index.js. Been a while since I've done Pebble development

**Comment by Allen-B1** [comment]
var Clay = require("pebble-clay");
var config = [
  //...
];
var clay = new Clay(config);

**Comment by Allen-B1** [comment]
```
var Clay = require("pebble-clay");
var config = [
  //...
];
var clay = new Clay(config);
```

**Comment by keegan-lillo** [comment]
Hmm it looks like cloudpebble is having trouble right now. I can't even get any compilation for my projects.

**Comment by Allen-B1** [comment]
Oh ok

**Comment by Allen-B1** [comment]
Should I close?

**Comment by keegan-lillo** [comment]
Yes please. Ask around in Discord. Maybe someone knows what's going on.
