### ISSUE TITLE
Send form data to external endpoint URL (via HTTP POST)

### ISSUE THREAD

**Issue by valorin** [pebble/clay#16]
When you're building a Timeline app, you usually need to send the user form data back to your server for processing - so it can be used to send pins to the user.

I know it's possible to inject JS so I'm assuming we could manually catch the form submission somewhere in the chain and POST off the data before it's returned to the user, but it'd be nice if that could be automatic. So all we need to do is define the endpoint URL and it'll send the data there for processing.

It'll also need to send the Pebble Account token, and Timeline token for obvious reasons. The latter is critical, and also really annoying to get from a config page at the moment.

**Comment by keegan-lillo** [comment]
This sort of defeats the main purpose of Clay. Besides it would make much more sense to run the XHTTP request from your app.js anyway. #20 will help with providing the config page with data obtained about the user.
