### ISSUE TITLE
Hide/Show items in the config page according to 'capabilities' of the watch

### ISSUE THREAD

**Issue by gregoiresage** [pebble/clay#18]
I would like to hide color options if the watch of the user is aplite.
I want to hide 'square' options or display cursom options if the watch is 'chalk'

With this [commit](https://github.com/pebble/clay/commit/5b2aba43123ca8b9f0fef54a28a5d4f709895886), we will be able to make such customization in the custom js but it would be cool to describe this behaviour in the config.json

``` json
[
{
  "type": "section",
  "items": [
    { "type": "heading", "defaultValue": "Enamel Demo" },
    {
      "type": "toggle",
      "id": "enableBackground",
      "appKey": "enableBackground",
      "label": "Enable Background",
      "capabilities" : ["aplite"] // this item will be displayed only for aplite
    },
    {
      "type": "color",
      "id": "background",
      "appKey": "background",
      "defaultValue": "FF0000",
      "label": "Background Color",
      "sunlight": true,
      "capabilities" : ["color"] // this item will be displayed only for watch with color
    },
    {
      "type": "select",
      "id": "font_size",
      "appKey": "font_size",
      "defaultValue": "1",
      "label": "Text Size",
      "capabilities" : ["bw", "rect"] // this item will be displayed only for rectangular watch without color
      "options": [
        { 
          "label": "Small", 
          "value": 0
        },
        { 
          "label": "Normal",
          "value": 1 
        },
        { 
          "label": "Large",
          "value": 2 
        }
      ]
    },
...
```

The list of capabilities would be : 
- color
- bw
- aplite/basalt/chalk
- round
- rect
- health
- ...

**Comment by keegan-lillo** [comment]
It's a neat idea but obtaining information other than what is directly returned from `Pebble.getActiveWatchInfo()` would mean that the capabilities would need to be calculated, which would become a pain to maintain each time Pebble comes up with a new feature. Ideally the `Pebble` global would have a method for obtaining the capabilities that Clay can use.

**Comment by gregoiresage** [comment]
ok so maybe just a filter based on the watch model would be a good start :p

**Comment by gregoiresage** [comment]
The [multiple config file feature](https://github.com/pebble/clay#handling-the-showconfiguration-and-webviewclosed-events-manually) fixes the problem for me

**Comment by keegan-lillo** [comment]
I still think that a capabilities property is a good idea. It keeps with the whole "it just works" idea.
