### ISSUE TITLE
Allow arbitrary data to be passed to the config page

### ISSUE THREAD

**Issue by keegan-lillo** [pebble/clay#20]
Once #19 gets merged, we will have access to the `.meta` property on the `ClayConfig`. We should allow developers to pass arbitrary information into this object as `.userData` or something. These can be added as an additional option in the `options` parameter of `Clay` constructor.

**Comment by gregoiresage** [comment]
Maybe a parameter to `generateUrl` would be a good idea if we want to have something more dynamic.
If we give an additional option to the ClayConfig contrsuctor, it will be static right ?

**Comment by keegan-lillo** [comment]
Not necessarily. We can either expose the `userData` on the `Clay` object itself allowing it to be manipulated, or provide a method to update the `userData`
