### ISSUE TITLE
Unknown message key when saving Clay config

### ISSUE THREAD

**Issue by mattmattmatt** [pebble/clay#3]
I'm using Cloudpebble with PebbleJS to write a simple app and integrated Clay in there.

It seems to work fine when it comes to building the config page from the configuration file. But when saving the settings, Cloudpebble is logging this error:
```
[PHONE] pebble-app.js:?: JavaScript Error:
Error: Unknown message key 'access_token'
    at Error (native)
    at sendAppMessage (eval at <anonymous> (runtime/internal/proxy:4:52)
    at Pebble.<anonymous> (clay.js:3:1196)
```

I [added the appKey to my `appinfo.json`](https://github.com/mattmattmatt/pushy-pebble/blob/57e534a7616101e99a782a2025b3f6b7956f7738/appinfo.json#L3) which I assume is what I'm supposed to do, but the Clay documentation is not very clear about this. Where does one define what in order to save the UI settings to the actual Pebble phone settings? And how would one do that when developing in Cloudpebble?

This is [the configuration file](https://github.com/mattmattmatt/pushy-pebble/blob/57e534a7616101e99a782a2025b3f6b7956f7738/src/clay-settings.js) used to build the config interface.

**Comment by keegan-lillo** [comment]
You need to add a matching in the "PebbleKit JS Message Keys" section of your project's settings in CloudPebble

**Comment by mattmattmatt** [comment]
Not sure I understand, where do I add these in my Cloudpebble settings?

![http://dl.dropboxusercontent.com/u/2730477/Screenshots/nCbd.png](http://dl.dropboxusercontent.com/u/2730477/Screenshots/nCbd.png)

**Comment by keegan-lillo** [comment]
It looks like that field is hidden for Pebble.js based apps :( You will need to manage the appMessage communication yourself. Have a look at this: https://github.com/pebble/clay#handling-the-showconfiguration-and-webviewclosed-events-manually

**Comment by keegan-lillo** [comment]
@mattmattmatt I'm going to close this. Let me know if the above doesn't work for you.
