### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by keegan-lillo** [pebble/clay#49]
Right now devs can use `Clay.meta.ActiveWatchInfo` to swap in different configs based on language, however this is not exactly maintainable.
#### Proposed solution:

Allow properties like `label`, `description` or `defaultValue` to be an object where the key is the ISO code for that locale and the value is the translation

``` javascript
{
  type: 'input',
  label: {
    en_US: 'Hello',
    fr_FR: 'Bonjour'
    // etc
  }
}
```

If there is no translation available for the user's language then the `en_US` value will be used. (This is the behavior of the native Pebble app and Pebble appstore)

There is no ETA for this and so please feel free to comment on any other solutions you think would work.

**Comment by keegan-lillo** [comment]
Adding an API to allow developers to set the language manually might also be a good idea. Particularly if they want to support more languages than the watch does

**Comment by gregoiresage** [comment]
we could also use templates (I don't know if it is the right term for that).

Translatable labels will be declared like that `label : "%STRING1%"` and in another section of the config file or somewhere else we would find `'STRING1' : 'string in english'`

**Comment by keegan-lillo** [comment]
I'm leaning towards @gregoiresage's idea which is similar to : https://developer.pebble.com/guides/tools-and-resources/internationalization/#using-locale-dictionaries

Devs would declare them with something like 

```js
// in the config
{
  type: 'input',
  label: '<strong>{{__('greeting')}}'
}
```

```js 
// app.js

var Clay = require('pebble-clay');
var clayConfig = require('./config.json');
var customFunction = require('./custom-function');
var clay = new Clay(clayConfig, customFunction, {
  locales: {
    en_US: require('./locales/en-us.json'),
    fr_FR: require('./locales/fr-fr.json'),
  },

  // This tells Clay whether not to make all the provided locales available to the config page
  bundleAllLocales: true 
});
```

```js
// ./locales/en-us.json
{
  "greeting": "Hello"
}
```

```js
// ./locales/fr-fr.json
{
  "greeting": "Bonjour"
}
```

```js
// ./custom-function.js

module.exports = function(minified) {
  var clayConfig = this;

  clayConfig.on(clayConfig.EVENTS.BEFORE_BUILD, function() {
    clayConfig.setLocale('fr_FR'); // usually can't do this, but bundleAllLocales is set to true 
  });
};
```

**Comment by keegan-lillo** [comment]
Not sure how the template syntax should work. It needs to be compatible with this I think http://minifiedjs.com/api/template.html

here are some options 

`{{ i18n.key }}`

`{{ _('key') }}`

`{{key}}` - for this one to be possible, I would need to run the template twice, but this is cleaner

**Comment by MathewReiss** [comment]
I'd argue for `{{key}}` (easiest to use for beginners to localization). `i18n.key` is also fine, but I'm already using `_('string')` for localization in Javascript anyways (per @gregoiresage 's recommendation, to match localization in C) so it wouldn't be that much effort (and stays consistent, which is nice).

**Comment by flocsy** [comment]
+1 any news/ETA about this feature?
