### ISSUE TITLE
Color item default value should be 'rounded' to the nearest Pebble color

### ISSUE THREAD

**Issue by gregoiresage** [pebble/clay#53]
If we enter an default value for the `color` item that is not one of the 64 Pebble colors, the colorpicker is gray.
Maybe the nearest pebble color for the default value should be displayed instead.

See https://github.com/kevincon/sprinkles/pull/3 , Kevin needs this :-p

**Comment by keegan-lillo** [comment]
I'm struggling to see the use case. Being a default value, why can't developers just set it to the correct value in the first place? The only reason I can think of is maybe migrating from old settings. In that case, I'd expect developers to do the migration themselves.

**Comment by gregoiresage** [comment]
I understand this is not a classic use case. I will implement the conversion in the custom js

**Comment by gregoiresage** [comment]
For the record, this is what I've added in my `Clay.EVENTS.AFTER_BUILD` to convert colors to Pebble ones

```
Clay.getItemsByType('color').map( function(item) {
      var color = item.get();
      var r = Math.floor((((color >> 16) & 0xFF) + 42) / 85) * 85;
      var g = Math.floor((((color >>  8) & 0xFF) + 42) / 85) * 85;
      var b = Math.floor((((color >>  0) & 0xFF) + 42) / 85) * 85;
      item.set((r << 16) + (g << 8) + b);
});
```

@kevincon you can close this issue if you want :)
