### ISSUE TITLE
Add <optgroup> to Select element

### ISSUE THREAD

**Issue by ygalanter** [pebble/clay#72]
Sometimes it is useful to separate options of Select element into subgroups, HTML Select element `<optgroup>` element to group related options. Would love to see it added to Clay

**Comment by keegan-lillo** [comment]
I need to confirm that this does something useful on the native android/ios implementations

**Comment by ygalanter** [comment]
Here's Slate implementation for comparasing: https://apps.getpebble.com/en_US/application/566642d77da16a2459000087

Load it and in config check option "Secondary info" (or "Bottom" of circle on PTR)

**Comment by keegan-lillo** [comment]
How would you see the config for this working?
something like?
```javascript
{
  "type": "select",
  "appKey": "flavor",
  "defaultValue": "grape",
  "label": "Favorite Flavor",
  "options": [
    {
      "label": "this is an optgroup",
      "value": [
        {
          "label": "First item of optgroup",
          "value": "one"
        },
        {
          "label": "second item of optgroup",
          "value": "two"
        }
      ]
    },
    {
      "label": "this is another optgroup",
      "value": [
        {
          "label": "First item of second optgroup",
          "value": "another one"
        },
        {
          "label": "second item of second optgroup",
          "value": "another two"
        }
      ]
    }
  ]
}
```

**Comment by ygalanter** [comment]
This hierarchical approach would be the best, but how would you handle just list of options without optgroups? Or could you support both formats - with and without optgroups?
Alternatively we can keep array flat like it is now, but add opening and closing elements for optgroups
