### ISSUE TITLE
Enable/Disable components based on toggle state

### ISSUE THREAD

**Issue by Spitemare** [pebble/clay#73]
It would be useful if in the config you could tie the state of a component to a toggle. For example:
```javascript
{
  "type": "toggle",
  "appKey": "ShowDate",
  "label": "Show Date",
  "defaultValue": true,
  "bind": [ "color-date" ]
},
{
  "type": "color",
  "id": "color-date",
  "appKey": "ColorDate",
  "label": "Date Color",
  "defaultValue": "FFFFFF",
  "sunlight": false
}
```

ColorDate would then be disabled if ShowDate is off.

I know such a thing can be done with a custom function, but it feels like a behavior used often enough to bake it into the framework.

**Comment by keegan-lillo** [comment]
You could probably achieve this bad adding an initialize function to the toggle component. I'm not going to add it to the roadmap but pull requests are always welcome.

**Comment by keegan-lillo** [comment]
Looking at this more closely, Clay is not set up to allow components to influence other components so this would require a pretty big structure change.
