### ISSUE TITLE
Allow integers as values for 'Select' options

### ISSUE THREAD

**Issue by gregoiresage** [pebble/clay#9]
I would like to configure my Select like below (with integers as values) and I want to get the selected item as an integer and not a string.
It would be easier to play with integers in the watchapp if I want different behaviors accordking to the chosen option.
Will it be possible to handle this use case ?

```
{
  "type": "select",
  "appKey": "flavor",
  "defaultValue": "grape",
  "label": "Favorite Flavor",
  "options": [
    { 
      "label": "", 
      "value": 0 
    },
    { 
      "label": "Berry",
      "value": 1 
    },
    { 
      "label": "Grape",
      "value": 2
    },
    { 
      "label": "Banana",
      "value": 3 
    }
  ],
  "attributes": {
    "required": "required"
  }
}

**Comment by keegan-lillo** [comment]
if you need to fiddle with the type before being sent to the watch you can manually handle the events. have a look at https://github.com/pebble/clay#handling-the-showconfiguration-and-webviewclosed-events-manually

You would just do `dict.flavor = parseInt(dict.flavor)`

**Comment by baranyaib90** [comment]
Hi,
I would also like to use numbers/integers in Radio Group as values.
(Mapping values to C enumeration type easily.)
So @keegan-lillo please re-consider this as feature request.
If the values were type independent, that would be great! (string, bool, integer)
Also:
If I want to use "defaultValue": "0", it will not work.
I have to place "." after every integer: "0."
This is very uncomfortable, and I guess not for the two of us.
Thank you in advance!

**Comment by clach04** [comment]
> if you need to fiddle with the type before being sent to the watch you can manually handle the events. have a look at https://github.com/pebble/clay#handling-the-showconfiguration-and-webviewclosed-events-manually
> 
> You would just do `dict.flavor = parseInt(dict.flavor)`

Hopefully save time for anyone else who wants to do this.

Since https://github.com/pebble/clay#migrating-from-v01x-to-v1x this has changed and requires `message_keys`

See `require('message_keys');` (2nd example) in Clay docs. Also:

    Pebble.addEventListener('webviewclosed', function(e) {
      if (e && !e.response) {
        return;
      }

      //console.log('e type ' + typeof(e)); // type object
      //console.log('e.response type ' + typeof(e.response));  // type string, contains json payload

      // Get the keys and values from each config item
      var dict = clay.getSettings(e.response);  // this is a dict, but the keys are numeric
      //console.log(JSON.stringify(dict));

      dict[messageKeys.YOUR_KEY_NAME_HERE] = parseInt(dict[messageKeys.YOUR_KEY_NAME_HERE]);
      //console.log(JSON.stringify(dict));

      // Send settings values to watch side
      Pebble.sendAppMessage(dict, function(e) {
        console.log('Sent config data to Pebble');
      }, function(e) {
        console.log('Failed to send config data!');
        console.log(JSON.stringify(e));
      });
    });
