### ISSUE TITLE
Webviewclosed event data is already decoded

### ISSUE THREAD

**Issue by gregoiresage** [pebble/clay#96]
https://github.com/pebble/clay/blob/master/index.js#L165

No need to decode it again, and this will create problem if the decoded string contains % characters for example

I'm on android 3.13.0

**Comment by keegan-lillo** [comment]
Looks like iOS has the same behavior, however the emulator does **not** decode the string. We could check for the presence of the `{` character and act accordingly until the SDK gets fixed... Feels a little icky though
